In [ ]:
import torch

In [ ]:
#1d
x = torch.empty(3)
print(x)

tensor([2.9210e-36, 0.0000e+00, 3.3631e-44])


In [ ]:
#2d
x = torch.empty(3,2)
print(x)

tensor([[2.9209e-36, 0.0000e+00],
        [5.0447e-44, 0.0000e+00],
        [       nan, 0.0000e+00]])


In [ ]:
#3d
x = torch.empty(3,3,4)
print(x)

tensor([[[2.2884e-36, 0.0000e+00, 2.2981e-43, 0.0000e+00],
         [       nan, 0.0000e+00, 7.5018e+28, 1.5564e+28],
         [4.7984e+30, 6.2121e+22, 1.8370e+25, 1.4603e-19]],

        [[2.7517e+12, 7.5338e+28, 3.0313e+32, 6.3828e+28],
         [1.4603e-19, 1.0899e+27, 6.8943e+34, 1.1835e+22],
         [7.0976e+22, 1.8515e+28, 4.1988e+07, 3.0357e+32]],

        [[2.7224e+20, 7.7782e+31, 4.7429e+30, 1.3818e+31],
         [1.7225e+22, 1.4602e-19, 1.8617e+25, 1.1835e+22],
         [4.3066e+21, 6.3828e+28, 1.4603e-19, 1.1578e+27]]])


In [ ]:
#4d
x = torch.empty(3,3,3,3)
print(x)

tensor([[[[7.9055e-37, 0.0000e+00, 6.4586e-42],
          [0.0000e+00, 7.7672e-37, 0.0000e+00],
          [7.7672e-37, 0.0000e+00, 3.5733e-43]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 3.5733e-43, 0.0000e+00]],

         [[1.0046e-41, 0.0000e+00, 7.7673e-37],
          [0.0000e+00, 7.7673e-37, 0.0000e+00],
          [3.5733e-43, 0.0000e+00, 0.0000e+00]]],


        [[[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 3.5733e-43],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 3.5733e-43, 0.0000e+00],
          [9.6872e-42, 0.0000e+00, 7.7674e-37]],

         [[0.0000e+00, 7.7674e-37, 0.0000e+00],
          [3.5733e-43, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]]],


        [[[0.0000e+00, 0.0000e+00, 3.5733e-43],
          [0.0000e+00, 1.0405e-41, 0.0000e+00],
          [7.7674e-37, 0

In [ ]:
#2d
x = torch.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [ ]:
#2d
x = torch.zeros(2,2,2,2)
print(x)

tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]])


In [ ]:
#2d
x = torch.ones(3,3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
#2d
x = torch.ones(3,3,dtype =torch.float32)
print(x.dtype)

torch.float32


In [ ]:
#2d
x = torch.ones(3,3,dtype =torch.float32)
print(x.size())

torch.Size([3, 3])


In [ ]:
x= torch.tensor([2.5,4.5])
print(x)

tensor([2.5000, 4.5000])


In [ ]:
x= torch.rand(2,2)
y= torch.rand(2,2)
print(x)
print(y)
print(x+y)

tensor([[0.1137, 0.2043],
        [0.1155, 0.3785]])
tensor([[0.7345, 0.7200],
        [0.4895, 0.0354]])
tensor([[0.8482, 0.9243],
        [0.6050, 0.4139]])


In [ ]:
x= torch.rand(2,2)
y= torch.rand(2,2)
print(x)
print(y)
z = torch.add(x,y)
print(z)

tensor([[0.3800, 0.3101],
        [0.3601, 0.9458]])
tensor([[0.7811, 0.5745],
        [0.7739, 0.0015]])
tensor([[1.1611, 0.8846],
        [1.1340, 0.9473]])


In [ ]:
x= torch.ones(2,2)
y= torch.ones(2,2)
#inplace addition
y.add_(x)
print(y)

tensor([[2., 2.],
        [2., 2.]])


In [ ]:
x= torch.ones(2,2)
y= torch.ones(2,2)
#z = x-y
z = torch.sub(x,y)
print(z)

tensor([[0., 0.],
        [0., 0.]])


In [ ]:
x= torch.ones(2,2)
y= torch.ones(2,2)
#z = x*y
z = torch.mul(x,y)
print(z)
y.mul_(x)

tensor([[1., 1.],
        [1., 1.]])


tensor([[1., 1.],
        [1., 1.]])

In [ ]:
x= torch.ones(2,2)
y= torch.ones(2,2)
#z = x/y
z = torch.div(x,y)
print(z)
y.div_(x)

tensor([[1., 1.],
        [1., 1.]])


tensor([[1., 1.],
        [1., 1.]])

In [ ]:
#slicing

In [ ]:
x = torch.rand(5,3)
print(x)
print(x[:,0])

tensor([[0.4440, 0.9141, 0.5672],
        [0.6296, 0.9658, 0.6267],
        [0.1560, 0.0436, 0.6084],
        [0.2930, 0.7473, 0.9534],
        [0.7230, 0.5342, 0.2811]])
tensor([0.4440, 0.6296, 0.1560, 0.2930, 0.7230])


In [ ]:
x = torch.rand(5,3)
print(x)
print(x[1,:]) #row no 1 all columns

tensor([[0.8880, 0.2099, 0.3086],
        [0.3133, 0.7832, 0.8583],
        [0.9491, 0.3105, 0.6745],
        [0.8940, 0.0797, 0.7084],
        [0.7510, 0.9545, 0.9992]])
tensor([0.3133, 0.7832, 0.8583])
